/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gcu.bake;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Statement;
/**
 *
 * @author Dziugas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        //this.setLocationRelativeTo(null);
       // algorithm that runs and sets status to ON-going if the lesson is on the same day as algorithm runs
       // algorithm that set status to Star-baker if all lessons of the same type have been completed
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jLabelLogin = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        usernameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login Form");

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 26)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMin)
                .addGap(26, 26, 26)
                .addComponent(jLabelClose)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        usernameLabel.setBackground(new java.awt.Color(204, 204, 204));
        usernameLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(255, 255, 255));
        usernameLabel.setText("Username:");

        passwordLabel.setBackground(new java.awt.Color(204, 204, 204));
        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordLabel.setText("Password:");

        jButtonLogin.setBackground(new java.awt.Color(102, 0, 102));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLabelLogin.setBackground(new java.awt.Color(204, 204, 204));
        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(102, 0, 102));
        jLabelLogin.setText("*Create account");
        jLabelLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
        });

        passwordText.setBackground(new java.awt.Color(204, 204, 204));
        passwordText.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        passwordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextActionPerformed(evt);
            }
        });

        usernameText.setBackground(new java.awt.Color(204, 204, 204));
        usernameText.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 349, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameLabel)
                    .addComponent(passwordLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passwordText, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(usernameText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(usernameText))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        Registration register = new Registration();
        register.setVisible(true);
        register.pack();
        register.setLocationRelativeTo(null);
        register.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked
// ******************************** GROUP'S FUNCTIONS **************************
    private Boolean adminVer(ResultSet rsA,String username, String password){
   try {
       while(rsA.next()){
           if (rsA.getString(1).equals(username) && rsA.getString(2).equals(password)) return true;
       } return false;
   } catch (SQLException e) {
       System.out.println(e);
   }
   return false;
}
private Boolean chefVer(ResultSet rsCh,String username, String password){
    try {
       while(rsCh.next()){
           if (rsCh.getString(1).equals(username) && rsCh.getString(2).equals(password)) return true;
       } return false;
   } catch (SQLException e) {
       System.out.println(e);
   }
   return false;
}
private Boolean custVer(ResultSet rsC,String username, String password){
    try {
       while(rsC.next()){
           if (rsC.getString(1).equals(username) && rsC.getString(2).equals(password)) return true;
       } return false;
   } catch (SQLException e) {
       System.out.println(e);
   }
   return false;
}
/*
* This function gets chef's ID to pass it to his dashboard, so the queries may be executed
*/
private Integer getChID (String usr, String pswd){
    Connection conn;
    String url = "jdbc:derby://localhost:1527/GCUBake";
    String getIDQuery = "SELECT \"IDCHEF\" FROM \"CHEFS\" WHERE \"EMAIL\" = ? AND \"PASSWORD\" = ?";
    try {
        conn = DriverManager.getConnection(url,"adam","adam");
        
        PreparedStatement stmnt = conn.prepareStatement(getIDQuery);
        stmnt.setString(1,usr);
        stmnt.setString(2,pswd);
        ResultSet rs = stmnt.executeQuery();
        if (rs.next()){
            Integer temp = rs.getInt(1);   
            //System.out.println(temp);
            stmnt.close();
            conn.close();
            rs.close();
            return temp;
        } return 0;
    } catch (SQLException e) {
        System.out.println(e);
    }
    return 0;
}
/*
* This function gets admin's ID to pass it to his dashboard, so the queries may be executed
*/
private Integer getAdID (String usr, String pswd){
    Connection conn;
    String url = "jdbc:derby://localhost:1527/GCUBake";
    String getIDQuery = "SELECT \"IDADMIN\" FROM \"ADMINS\" WHERE \"EMAIL\" = ? AND \"PASSWORD\" = ?"; //Unfortunately we can't do ? in the place of table name so we have to copy paste that
    // or maybe we can but idk how :D
    try {
        conn = DriverManager.getConnection(url,"adam","adam");
        
        PreparedStatement stmnt = conn.prepareStatement(getIDQuery);
        stmnt.setString(1,usr);
        stmnt.setString(2,pswd);
        ResultSet rs = stmnt.executeQuery();
        if (rs.next()){
            Integer temp = rs.getInt(1);   
            //System.out.println(temp);
            stmnt.close();
            conn.close();
            rs.close();
            return temp;
        } return 0;
    } catch (SQLException e) {
        System.out.println(e);
    }
    return 0;
}
/*
* This function gets customer's ID to pass it to his dashboard, so the queries may be executed
*/
private Integer getCuID (String usr, String pswd){
    Connection conn;
    String url = "jdbc:derby://localhost:1527/GCUBake";
    String getIDQuery = "SELECT \"IDCUSTOMER\" FROM \"CUSTOMERS\" WHERE \"EMAIL\" = ? AND \"PASSWORD\" = ?"; //Unfortunately we can't do ? in the place of table name so we have to copy paste that
    // or maybe we can but idk how :D
    try {
        conn = DriverManager.getConnection(url,"adam","adam");
        
        PreparedStatement stmnt = conn.prepareStatement(getIDQuery);
        stmnt.setString(1,usr);
        stmnt.setString(2,pswd);
        ResultSet rs = stmnt.executeQuery();
        if (rs.next()){
            Integer temp = rs.getInt(1);   
            //System.out.println(temp);
            stmnt.close();
            conn.close();
            rs.close();
            return temp;
        } return 0;
    } catch (SQLException e) {
        System.out.println(e);
    }
    return 0;
}

// ******************************** END OF GROUP'S FUNCTIONS **************************

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String username = usernameText.getText();
        String password = new String (passwordText.getPassword());
        Connection conn;
        String url = "jdbc:derby://localhost:1527/GCUBake";
        
            try{
                conn = DriverManager.getConnection(url,"adam","adam");
                Statement st = conn.createStatement();
                Statement st2 = conn.createStatement();
                Statement st3 = conn.createStatement();
                String sqlA = "SELECT \"EMAIL\",\"PASSWORD\" FROM \"ADMINS\"";
                String sqlCh = "SELECT \"EMAIL\",\"PASSWORD\" FROM \"CHEFS\"";
                String sqlC = "SELECT \"EMAIL\",\"PASSWORD\" FROM \"CUSTOMERS\"";
                
                ResultSet rsA = st.executeQuery(sqlA);
                ResultSet rsCh = st2.executeQuery(sqlCh);
                ResultSet rsC = st3.executeQuery(sqlC);
                if(adminVer(rsA,username,password)){
                        Integer AdminID = getAdID(username,password);
                        System.out.println(AdminID);
                        if (AdminID !=0 ){
                        Main_Admin mainAd = new Main_Admin(AdminID.toString());
                        mainAd.setVisible(true);
                        mainAd.pack();
                        mainAd.setLocationRelativeTo(null);
                        mainAd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                        }
                } else {
                    if (chefVer(rsCh,username,password)){
                        Integer ChefID = getChID(username,password); //This and the function above 
                        //I use Integer because the ID in database is in int type. Integer will allow us to convert it into String and use it in future queries.
                        System.out.println(ChefID);
                        if (ChefID != 0) {
                        String schID = ChefID.toString();
                        Main_chef mainCh = new Main_chef(schID);
                        mainCh.setVisible(true);
                        mainCh.pack();
                        mainCh.setLocationRelativeTo(null);
                        mainCh.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                        }
                    } else {
                        //THAT'S YOURS TO FIGURE OUT, BASICALLY COPY PASTE FROM ABOVE BUT ANALYZE IT FOR YOURSELF
                        if (custVer(rsC,username,password)){
                        Main main = new Main();
                        main.setVisible(true);
                        main.pack();
                        main.setLocationRelativeTo(null);
                        main.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        this.dispose();
                     } else {
                            JOptionPane.showMessageDialog(rootPane,"Username do not match OR You have not registered yet");
                        }
                }
                }
                conn.close();
                st.close();
                st2.close();
                st3.close();
            } catch(SQLException e){
               // JOptionPane.showMessageDialog(rootPane,"Username do not match OR You have not registered yet");
               System.out.println(e);
            }
            
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void passwordTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
